name: Component tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start backend server
        run: |
          cd backend
          npm start &
        env:
          CI: true

      - name: Start frontend server
        run: |
          cd frontend
          npm start &
        env:
          CI: true

      - name: Wait for servers to be ready
        run: npx wait-on http://localhost:3000 http://localhost:3001

      - name: Cypress run
        uses: cypress-io/github-action@v6
         