name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      # Configura o serviço Docker para rodar o backend na porta 3001
      backend:
        image: your-backend-image:latest  # Substitua pela imagem Docker do seu backend
        ports:
          - 3001:3001
        options: --name backend
      # Configura o serviço Docker para rodar o frontend na porta 3000
      frontend:
        image: your-frontend-image:latest  # Substitua pela imagem Docker do seu frontend
        ports:
          - 3000:3000
        options: --name frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Instalação e execução dos testes de API
      - name: Install Backend modules and start server
        run: |
          npm install
          npm run install:backend
          npm run start:server &

      # Aguarda até que o servidor backend esteja pronto
      - name: Wait for backend to start
        run: |
          npx wait-on http://localhost:3001
          echo "Backend server is ready!"

      # Instalação e execução dos testes de frontend
      - name: Install Frontend modules and start server
        run: |
          npm run install:frontend
          npm run start:frontend &

      # Aguarda até que o servidor frontend esteja pronto
      - name: Wait for frontend to start
        run: |
          npx wait-on http://localhost:3000
          echo "Frontend server is ready!"

      # Executa os testes E2E (backend e frontend) usando Cypress
      - name: Run E2E tests 🧪
        run: npm run test:e2e
        env:
          CYPRESS_BASE_URL: http://localhost:3000  # URL base para os testes do Cypress
